### PR TITLE
Update dependency versions

### PR DESCRIPTION
**Pull request by djbower**
Minimum requirements for pandas 1.3.0.

### CODE REVIEW

**Review by ZGainsforth — CHANGES_REQUESTED** [review]
The versions should also be updated  in the readme at the same time.  Thanks!

**Comment by djbower** [comment]
Both `README.rst` and `setup.py` are now consistent in terms of the dependencies.

**Comment by djbower** [comment]
@ZGainsforth  Do I need to do anything else or can this pull request now be accepted? Thanks!

**Comment by ZGainsforth** [comment]
Thank you!

**Pull request merged**
